### ISSUE TITLE
running master fails

### ISSUE THREAD

**Issue by luisrudge** [onefinestay/react-daterange-picker#28]
![image](https://cloud.githubusercontent.com/assets/941075/7498007/2f09f4a4-f3f4-11e4-9b23-173562eb67fa.png)

**Comment by jkimbo** [comment]
Yep I can replicate this and #29 should fix it. @luisrudge can you check? The issue was that the gulp-render dependency that we use to generate the markup was using an older version of React so when we upgraded there were some weird conflicts. The solution was to drop it in favour of a hand rolled one. 

Planning on actually rolling all of this into the webpack build eventually so we can drop this double build process.

**Comment by luisrudge** [comment]
@jkimbo that works! Can you publish this to npm? Thanks!

**Comment by jkimbo** [comment]
Published to npm as v0.6.1

**Comment by luisrudge** [comment]
Thanks! :)
