### ISSUE TITLE
Highlight current date

### ISSUE THREAD

**Issue by jimmyn** [onefinestay/react-daterange-picker#42]
Is there a way to highlight current date?

**Comment by AndrewIngram** [comment]
We can put in a prop that's passed to the `CalendarDate` component that indicates whether it's the current date. How we actually display that visually is a bit trickier, since the UI is already fairly cluttered with different colours and visual cues. But giving you access to the prop means you can swap out the component and style it however you like.

**Comment by jimmyn** [comment]
I think this is a handful feature =)
